### ISSUE TITLE
Missing label

### ISSUE THREAD

**Issue by khoids** [VinAIResearch/PhoNER_COVID19#1]
Line `14937` in [test_word.conll](https://github.com/VinAIResearch/PhoNER_COVID19/blob/main/data/word/test_word.conll) is missing label 🙂.
Also, the label of Chợ_Rẫy at line `48095` in [dev_word.conll](https://github.com/VinAIResearch/PhoNER_COVID19/blob/main/data/word/dev_word.conll) must be I-ORGANIZATION (not O-ORGANIZATION)

**Comment by joey234** [comment]
Thank you so much for pointing this out. We've fix these errors.
